/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanetsIndexRouteImport } from './routes/planets/index'
import { Route as PlanetsIdRouteImport } from './routes/planets/$id'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsIndexRoute = PlanetsIndexRouteImport.update({
  id: '/planets/',
  path: '/planets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsIdRoute = PlanetsIdRouteImport.update({
  id: '/planets/$id',
  path: '/planets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/planets/$id': typeof PlanetsIdRoute
  '/planets': typeof PlanetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/planets/$id': typeof PlanetsIdRoute
  '/planets': typeof PlanetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/planets/$id': typeof PlanetsIdRoute
  '/planets/': typeof PlanetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/planets/$id' | '/planets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/planets/$id' | '/planets'
  id: '__root__' | '/' | '/chat' | '/planets/$id' | '/planets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  PlanetsIdRoute: typeof PlanetsIdRoute
  PlanetsIndexRoute: typeof PlanetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets/': {
      id: '/planets/'
      path: '/planets'
      fullPath: '/planets'
      preLoaderRoute: typeof PlanetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets/$id': {
      id: '/planets/$id'
      path: '/planets/$id'
      fullPath: '/planets/$id'
      preLoaderRoute: typeof PlanetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  PlanetsIdRoute: PlanetsIdRoute,
  PlanetsIndexRoute: PlanetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
